### ISSUE TITLE
Check for Exercise/Solution extensions for Jupyter

### ISSUE THREAD

**Issue by adatz273** [dokempf/dune-jupyter-course#6]
check extensions (also) working for jupyter lab

**Comment by dokempf** [comment]
Decision after meeting today: We use the classic notebook extension for now and will see what solutions for JupyterLab will come up in the future - there is other block issues for the transition anyway.

**Comment by dokempf** [comment]
There may be some other possibilities in JupyterLab: https://discourse.jupyter.org/t/hiding-spoilers-answers-cells/4252/2

**Comment by adatz273** [comment]
Final Decision: Take the exercise extensions from jupyter_contrib_nbextensions, which work nicely for the notebook and, as described above, postpone decision for jupyter lab untill it becomes relevant.
